package com.shopping.cloud.common.userTab;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

@ApiModel(value = "用户对象")
public class UserTab {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.id
     *
     * @mbggenerated
     */
    @ApiModelProperty("主键ID")
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.email
     *
     * @mbggenerated
     */
    @ApiModelProperty("邮箱地址")
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.password
     *
     * @mbggenerated
     */
    @ApiModelProperty("密码")
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.pay_password
     *
     * @mbggenerated
     */
    @ApiModelProperty("支付密码")
    private String payPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.mobile
     *
     * @mbggenerated
     */
    @ApiModelProperty("手机号")
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.nickname
     *
     * @mbggenerated
     */
    @ApiModelProperty("昵称")
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.qrcode_url
     *
     * @mbggenerated
     */
    @ApiModelProperty("二维码地址（乐富号作为唯一标识）")
    private String qrcodeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.state
     *
     * @mbggenerated
     */
    @ApiModelProperty("用户状态(1:正常 2:冻结 3:锁定)")
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.sex
     *
     * @mbggenerated
     */
    @ApiModelProperty("性别(0:保密 1:男 2:女)")
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.auth_state
     *
     * @mbggenerated
     */
    @ApiModelProperty("实名认证状态(0:草稿状态 1:待认证 2-审核驳回 3-认证成功 4-审核认证通过驳回))")
    private Integer authState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.head_url
     *
     * @mbggenerated
     */
    @ApiModelProperty("头像的完整路径")
    private String headUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.referrer_id
     *
     * @mbggenerated
     */
    @ApiModelProperty("推荐人ID")
    private Long referrerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.orginal_referrer_id
     *
     * @mbggenerated
     */
    @ApiModelProperty("原始推荐人ID")
    private Long orginalReferrerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.create_time
     *
     * @mbggenerated
     */
    @ApiModelProperty("创建时间")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.creater
     *
     * @mbggenerated
     */
    @ApiModelProperty("创建人ID")
    private Long creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.modifier
     *
     * @mbggenerated
     */
    @ApiModelProperty("修改人ID")
    private Long modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.modify_time
     *
     * @mbggenerated
     */
    @ApiModelProperty("更新时间")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.dna
     *
     * @mbggenerated
     */
    @ApiModelProperty("推荐关系链")
    private String dna;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.type
     *
     * @mbggenerated
     */
    @ApiModelProperty("1表示消费会员，2表示企业会员")
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.reg_source
     *
     * @mbggenerated
     */
    @ApiModelProperty("注册来源（1-android 2-ios 3-微信 4-其他）")
    private Integer regSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.openid
     *
     * @mbggenerated
     */
    @ApiModelProperty("openid")
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.wechat_nickname
     *
     * @mbggenerated
     */
    @ApiModelProperty("公众号昵称")
    private String wechatNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.wechat_id
     *
     * @mbggenerated
     */
    @ApiModelProperty("微信ID")
    private String wechatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.love_id
     *
     * @mbggenerated
     */
    @ApiModelProperty("乐富号（作为邀请码）")
    private Long loveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tab.login_time
     *
     * @mbggenerated
     */
    @ApiModelProperty("最近登录时间")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.id
     *
     * @return the value of user_tab.id
     *
     * @mbggenerated
     */
    @ApiModelProperty("生日")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date birthDay;

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.id
     *
     * @param id the value for user_tab.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.email
     *
     * @return the value of user_tab.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.email
     *
     * @param email the value for user_tab.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.password
     *
     * @return the value of user_tab.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.password
     *
     * @param password the value for user_tab.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.pay_password
     *
     * @return the value of user_tab.pay_password
     *
     * @mbggenerated
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.pay_password
     *
     * @param payPassword the value for user_tab.pay_password
     *
     * @mbggenerated
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.mobile
     *
     * @return the value of user_tab.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.mobile
     *
     * @param mobile the value for user_tab.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.nickname
     *
     * @return the value of user_tab.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.nickname
     *
     * @param nickname the value for user_tab.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.qrcode_url
     *
     * @return the value of user_tab.qrcode_url
     *
     * @mbggenerated
     */
    public String getQrcodeUrl() {
        return qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.qrcode_url
     *
     * @param qrcodeUrl the value for user_tab.qrcode_url
     *
     * @mbggenerated
     */
    public void setQrcodeUrl(String qrcodeUrl) {
        this.qrcodeUrl = qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.state
     *
     * @return the value of user_tab.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.state
     *
     * @param state the value for user_tab.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.sex
     *
     * @return the value of user_tab.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.sex
     *
     * @param sex the value for user_tab.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.auth_state
     *
     * @return the value of user_tab.auth_state
     *
     * @mbggenerated
     */
    public Integer getAuthState() {
        if(null==authState){
            authState = Constant.AUTH_INITIAL_SATE;
        }
        return authState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.auth_state
     *
     * @param authState the value for user_tab.auth_state
     *
     * @mbggenerated
     */
    public void setAuthState(Integer authState) {
        this.authState = authState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.head_url
     *
     * @return the value of user_tab.head_url
     *
     * @mbggenerated
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.head_url
     *
     * @param headUrl the value for user_tab.head_url
     *
     * @mbggenerated
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.referrer_id
     *
     * @return the value of user_tab.referrer_id
     *
     * @mbggenerated
     */
    public Long getReferrerId() {
        return referrerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.referrer_id
     *
     * @param referrerId the value for user_tab.referrer_id
     *
     * @mbggenerated
     */
    public void setReferrerId(Long referrerId) {
        this.referrerId = referrerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.orginal_referrer_id
     *
     * @return the value of user_tab.orginal_referrer_id
     *
     * @mbggenerated
     */
    public Long getOrginalReferrerId() {
        return orginalReferrerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.orginal_referrer_id
     *
     * @param orginalReferrerId the value for user_tab.orginal_referrer_id
     *
     * @mbggenerated
     */
    public void setOrginalReferrerId(Long orginalReferrerId) {
        this.orginalReferrerId = orginalReferrerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.create_time
     *
     * @return the value of user_tab.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.create_time
     *
     * @param createTime the value for user_tab.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.creater
     *
     * @return the value of user_tab.creater
     *
     * @mbggenerated
     */
    public Long getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.creater
     *
     * @param creater the value for user_tab.creater
     *
     * @mbggenerated
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.modifier
     *
     * @return the value of user_tab.modifier
     *
     * @mbggenerated
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.modifier
     *
     * @param modifier the value for user_tab.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.modify_time
     *
     * @return the value of user_tab.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.modify_time
     *
     * @param modifyTime the value for user_tab.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.dna
     *
     * @return the value of user_tab.dna
     *
     * @mbggenerated
     */
    public String getDna() {
        return dna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.dna
     *
     * @param dna the value for user_tab.dna
     *
     * @mbggenerated
     */
    public void setDna(String dna) {
        this.dna = dna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.type
     *
     * @return the value of user_tab.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.type
     *
     * @param type the value for user_tab.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.reg_source
     *
     * @return the value of user_tab.reg_source
     *
     * @mbggenerated
     */
    public Integer getRegSource() {
        return regSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.reg_source
     *
     * @param regSource the value for user_tab.reg_source
     *
     * @mbggenerated
     */
    public void setRegSource(Integer regSource) {
        this.regSource = regSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.openid
     *
     * @return the value of user_tab.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.openid
     *
     * @param openid the value for user_tab.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.wechat_nickname
     *
     * @return the value of user_tab.wechat_nickname
     *
     * @mbggenerated
     */
    public String getWechatNickname() {
        return wechatNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.wechat_nickname
     *
     * @param wechatNickname the value for user_tab.wechat_nickname
     *
     * @mbggenerated
     */
    public void setWechatNickname(String wechatNickname) {
        this.wechatNickname = wechatNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.wechat_id
     *
     * @return the value of user_tab.wechat_id
     *
     * @mbggenerated
     */
    public String getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.wechat_id
     *
     * @param wechatId the value for user_tab.wechat_id
     *
     * @mbggenerated
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.love_id
     *
     * @return the value of user_tab.love_id
     *
     * @mbggenerated
     */
    public Long getLoveId() {
        return loveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.love_id
     *
     * @param loveId the value for user_tab.love_id
     *
     * @mbggenerated
     */
    public void setLoveId(Long loveId) {
        this.loveId = loveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tab.login_time
     *
     * @return the value of user_tab.login_time
     *
     * @mbggenerated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tab.login_time
     *
     * @param loginTime the value for user_tab.login_time
     *
     * @mbggenerated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    public Date getBirthDay() {
        return birthDay;
    }

    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }
}